application: cloudsnap
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /backup
  script: main.app
  login: admin

- url: /cleanup
  script: main.app
  login: admin

libraries:
- name: jinja2
  version: 2.6
- name: markupsafe
  version: 0.15
