script: nosetests --with-spec --spec-color --with-gae --without-sandbox --gae-lib-root google_appengine --gae-application cloudsnap
language: python
python:
  - 2.7
install: make setup &> /dev/null
before_script:
  - pip install virtualenvwrapper pinocchio &> /dev/null
  - export WORKON_HOME=$HOME/dev
  - source /home/vagrant/virtualenv/python2.7/bin/virtualenvwrapper.sh &> /dev/null
  - add2virtualenv cloudsnap
